### ISSUE TITLE
Yarn 2 PnP stricter module resolution and mocha detection

### ISSUE THREAD

**Issue by vonagam** [stalniy/bdd-lazy-var#117]
Yarn 2 introduced new alternative stricter resolution system for modules - [Plug'n'Play](https://yarnpkg.com/features/pnp).

The problem: `bdd-lazy-var` does not have `mocha` as a dependency but still [relies](https://github.com/stalniy/bdd-lazy-var/blob/a367d375d9d6cd0c1238e91ddd575694d01a745d/lib/interface/index.js#L4) on it being resolvable during framework detection. PnP system does not allow that.

There is ["loose" mode](https://yarnpkg.com/features/pnp#pnp-loose-mode) that makes it work, but it still generates warnings about ambiguity and unsoundness of such require call.

**Comment by stalniy** [comment]
Mocha is a peer dependency. Does it mean yarn PnP doesn’t support peerdeps?

**Comment by vonagam** [comment]
If it was declared as peer dependency it would have worked.
Currently there is no peer dependencies in package.json to support both `mocha` and `jasmine`.

**Comment by stalniy** [comment]
You are right. For some reason I thought they are all optional peerdeps. Need to change this. 

If you have time PR is very welcome!

**Comment by vonagam** [comment]
This requires only small changes to `package.json` but i don't know current supported version range for `mocha` (and `jasmine` or `jest` which can be added too), unless you want to use wildcard.

**Comment by stalniy** [comment]
this ones works for sure:

```
  "optionalDependencies": {
    "mocha": "^4.0.0 || ^3.0.0 || ^2.3.0 || ^5.0.0 || ^6.0.0",
    "jasmine-core": "^2.0.0 || ^3.0.0",
    "jest": "^20.0.0 || ^22.0.0 || ^23.0.0 || ^24.0.0"
  },
```

just need to use `peerDeps` + `peerDepsMeta`
