### ISSUE TITLE
Support of Jest?

### ISSUE THREAD

**Issue by dezoxel** [stalniy/bdd-lazy-var#23]
Hey Sergey,

We use [React](https://reactjs.org/) and [create-react-app ](https://github.com/facebookincubator/create-react-app) in our projects. Do you plan to support [Jest](https://facebook.github.io/jest/)?

Maybe you could point me in the direction of how to implement it by myself?

**Comment by stalniy** [comment]
Hi

I didn't plan to do that but PRs are very welcome :)

About implementation:
1. you need to understand whether best allow to add additional UI like mocha. 
2. you need to understand how jest exposes currentTest and whether it creates prototype tree for nested tests
3. You need to know how to access patent suite from currentTest
4. Add implementation to https://github.com/stalniy/bdd-lazy-var/tree/master/lib/interface. check how it was done for mocha 

Ps: sorry for the delayed reply

**Comment by stalniy** [comment]
I did some refactoring of the project so now it should be clearer what to do. Unfortunetely there are some mocha internals in `lib/interface.js` which should be moved in `lib/interface/mocha.js` and passed as a callback function

**Comment by stalniy** [comment]
as far as I can tell `jest` was written based on `jasmine2` that means that we need to add support for `jasmine2` and it should work as well for jest.

**PS**: if you run `npm i jest` you will find `jest-jasmine2` module in your node_modules

**Comment by stalniy** [comment]
I finished with implementation for `jasmine2` you can take a look at ede928c20038ba0228e08faeb9a6701d0e5415b8 and `lib/interface/jasmine.js` to understand how to do this for `jest`

**Comment by stalniy** [comment]
published 2.0 to npm

**Comment by stalniy** [comment]
added support for jest and published 2.1.1 to npm

**Comment by dezoxel** [comment]
Wow, awesome! We will try it soon and I'll give a feedback, thanks a lot!
