### ISSUE TITLE
Improve typings for sharedExamplesFor

### ISSUE THREAD

**Issue by nzacca** [stalniy/bdd-lazy-var#46]
Hello!

The current typings for `sharedExamplesFor` are defined as:

`export function sharedExamplesFor(summary: string, implementation: () => void): void;`
Source: https://github.com/stalniy/bdd-lazy-var/blob/master/index.d.ts#L7

I believe these need to be changed as follows to coincide with the signature from `itBehavesLike` and the documentation in the readme:

`export function sharedExamplesFor(summary: string, implementation: (...vars: any[]) => void): void;`

We're currently receiving the following error when attempting to define parameters on `sharedExamplesFor`:

```
[ts] Argument of type '(a: any) => void' is not assignable to parameter of type '() => void'.
```

**Comment by stalniy** [comment]
Hello 

 You are correct :) will fix in few hours

Thanks for the issue!

**Comment by stalniy** [comment]
fixed in `bdd-lazy-var@2.2.5`

**Comment by nzacca** [comment]
@stalniy Thank you very much!

Was the `global` one supposed to be updated too?

https://github.com/stalniy/bdd-lazy-var/blob/master/index.d.ts#L14

**Comment by stalniy** [comment]
Ah... my bad. Sure!

**Comment by stalniy** [comment]
try 2.2.6 version. I removed duplication in d.ts files so now I will not forget to update it in 2 places ))

**Comment by nzacca** [comment]
@stalniy Perfect! Nice refactor. Thank you so much!
