### ISSUE TITLE
bdd-lazy-var/rspec missing in 2.4.2

### ISSUE THREAD

**Issue by dkreft** [stalniy/bdd-lazy-var#50]
Hey, what happened to `bdd-lazy-var/rspec` (which was added per issue #18)?

```
dkreft@tmlappy:~/pomodoro> npm test

> pomodoro-timer@0.0.1 test /Users/dkreft/pomodoro
> NODE_ENV=test mocha

/Users/dkreft/pomodoro/node_modules/mocha/lib/mocha.js:214
      throw new Error('invalid interface "' + name + '"');
      ^

Error: invalid interface "bdd-lazy-var/rspec"
    at Mocha.ui (/Users/dkreft/pomodoro/node_modules/mocha/lib/mocha.js:214:13)
    at Object.<anonymous> (/Users/dkreft/pomodoro/node_modules/mocha/bin/_mocha:516:7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm ERR! Test failed.  See above for more details.
```

```
dkreft@tmlappy:~/pomodoro> npm ls bdd-lazy-var
pomodoro-timer@0.0.1 /Users/dkreft/pomodoro
└── bdd-lazy-var@2.4.2 
```

```
dkreft@tmlappy:~/pomodoro> cat test/mocha.opts
--require babel-core/register
--require babel-polyfill
--ui bdd-lazy-var/rspec
--recursive
```

**Comment by stalniy** [comment]
`rspec` was removed in 2.x version. All existing UIs now use behavior of `rspec`. That's why there is no need for a separate implementation.

Just replace `bdd-lazy-var/rspec` with `bdd-lazy-var/global` and everything should be fine

**Comment by dkreft** [comment]
Cool...it's just it seems like the POLA was violated on this one. I was expecting to see something in the documentation about this (or did I miss it?).

**Comment by stalniy** [comment]
Hmm... I thought I documented this in releases :) But I forgot, sorry for this. Updated release: https://github.com/stalniy/bdd-lazy-var/releases/tag/v2.0.0

**Details**:
I wrote about this in issue created by you: https://github.com/stalniy/bdd-lazy-var/issues/14#issuecomment-356014046

Later I added a commit to that issue: https://github.com/stalniy/bdd-lazy-var/commit/ede928c20038ba0228e08faeb9a6701d0e5415b8

It was done for 2.0 release.

**Comment by stalniy** [comment]
Close as there are no action items on this
