### ISSUE TITLE
Add eslint rule/plugin to handle $foo global vars

### ISSUE THREAD

**Issue by stalniy** [stalniy/bdd-lazy-var#56]
**Requirements**:
- [ ] perceive all variables with name `$*` as defined
- [ ] if `onlyDefined` option is set to `true`, then additionally check whether the lazy var is defined with `def`
- [ ] if `noDynamicName` option is set to `true`, then rule will not allow to use dynamically defined lazy vars 
- [ ] allow to specify dialects (`bdd`, `bdd/getter`, `bdd/global`) to check defined lazy vars
- [ ] adds `its`, `def`, `subject`, `get`, `sharedExamplesFor`, `includeExamplesFor`, `itBehavesLike` and `is` to global variables
- [ ] this rule must play nice with `no-undef` rule or substitute it (implement its behavior inside)

**Comment by stalniy** [comment]
I started the work in `feat/eslint-rule` branch, probably it need to be a plugin not just a few rules

**Comment by Kukunin** [comment]
I did work around this issue by disabling the rule specifically for tests:

```
    "overrides": [
        {
            "files": ["*.test.js"],
            "rules": {
                "no-undef": 0
            }
        }
    ],
```

in `eslintrc.js`

**Comment by vhoyer** [comment]
> I did work around this issue by disabling the rule specifically for tests:
> 
> ```
>     "overrides": [
>         {
>             "files": ["*.test.js"],
>             "rules": {
>                 "no-undef": 0
>             }
>         }
>     ],
> ```
> 
> in `eslintrc.js`

not Ideal to ignore the rule, but it's a good enough workaround while we don't have the real deal :shrug:

**Comment by stalniy** [comment]
Another good workaround which I saw in the wild is `$.name`. You have almost the same as with global interface using getter interface (bdd-lazy-var/getter)


```js
const { get } = require('bdd-lazy-var/getter')
global.$ = get
```

**Comment by stalniy** [comment]
Ok. Yeah. Looks like bug. Will fix it tomorrow. Thanks!

**Comment by stalniy** [comment]
This will be redundant with a new version. The API is shown in [this comment](https://github.com/stalniy/bdd-lazy-var/issues/97#issuecomment-774303775)
