### ISSUE TITLE
Cypress support

### ISSUE THREAD

**Issue by guy333** [stalniy/bdd-lazy-var#68]
Can this be used in cypress, Where there is no access to `new Mocha()` ?

**Comment by stalniy** [comment]
I think yes. What you need to find is how to change mocha ui in cypress

**Comment by stalniy** [comment]
https://github.com/cypress-io/cypress/issues/1263

**Comment by stalniy** [comment]
Nothing I can do to help. You need to make a PR to cypress or ask them to implement that feature

**Comment by atryshkin** [comment]
Hi
I tried to connect.
You have access to Mocha in bdd-lazy-var/index.js via global.Mocha or global.Cypress.mocha._mocha.Mocha.
I have added an interface but the tests are not running

```
node_modules/bdd-lazy-var/index.js

var _mocha = global.Cypress ? global.Mocha : mocha__default['default']
```

```
cypress/support/index.ts

mocha.ui('bdd-lazy-var');
```
