### ISSUE TITLE
Use in PhantomJS?

### ISSUE THREAD

**Issue by tylercollier** [stalniy/bdd-lazy-var#8]
This package looks awesome. At first I was trying to use it when running my tests in PhantomJS, and I was getting errors like `Error: Cannot find module "fs"`, and then I realized phantom wouldn't have access to the file system since it's a browser. I found [this page](http://phantomjs.org/api/fs/) that makes it look like it *could* use `fs`?... but that page doesn't really tell me anything useful. So, do you know, is it possible to use this from within a browser, such as PhantomJS?

**Comment by tylercollier** [comment]
Hmm. I'm using karma as my test runner, and using its mocha plugin, so it must be possible to run mocha in Phantom.

**Comment by stalniy** [comment]
For browser env, you need to use `bdd_lazy_var*.js` files depending on the format which you prefer (regular `get` function, getters on the `ge`t function or global getters)

You can check `spec/karma.conf.js` and scripts section inside package.json for more details as this library has tests which are run under travis CI in both nodejs and FireFox envs

**Comment by tylercollier** [comment]
Ah! I saw that in the README but it didn't hit me because I was thinking "I'm in node". But yes, I'm in a browser when in PhantomJS.

I took a look at the places you mentioned and request more help. I can see you really know what you're doing here; great code organization in this library!

I want to use the 'global' getters, so how would I do that?

Here's what I'm trying (coffeescript):

```
{ def, subject } = require 'bdd-lazy-var/bdd_lazy_var_global'
```

In this case, `def` and `subject` are undefined, so that's not right. I was expecting perhaps `window.def` and `window.subject` to exist, but no, nor `global.def/subject`.

I know the require statement is doing *something*, because if I DON'T do that, then when I run

```
mocha = new Mocha
	ui: 'bdd-lazy-var/global'
```

I get `Error: invalid interface "bdd-lazy-var/global"`.

Next I tried looking at the `package.json` scripts examples, which has e.g.

```
"test-browser-global-ui": "karma start -u bdd-lazy-var/global
```

so I tried running karma like this:

```
karma start -u bdd-lazy-var/global
```

But this makes no difference. I can't find documentation on `-u` (or `--src`). Using some invalid thing does *not* give an error, e.g. `karma start -u FAKETHING`, so it seems like karma is ignoring my `-u`. I'm using karma 0.13.22.

Bonus: I'm using webpack with karma. When I do `require 'bdd-lazy-var/bdd_lazy_var_global'`, it says `This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.` Is there a non pre-built file? Or maybe what I think would be called a UMD version?

**Comment by stalniy** [comment]
You need to require interface manually, for example put it in `files` of karma configuration and then in your mocha configuration you need to specify `ui` option. So, something like this should work. 
```js
require('bdd-lazy-var/bdd_lazy_var_global');
new Mocha(ui: 'bdd-lazy-var/global')
```

**Comment by tylercollier** [comment]
To get this going, here's what I did:

* First, I did not bother modifying my `package.json` scripts section, to add command line arguments, as this project's `package.json` does. I think that's needed so the package can run tests using the 3 diferent 'getter' styles, but since I only wanted one (global), I just hard coded that in my karma config as I'll show below.

* I modified my karma config as follows (coffeescript), see comments inline:

```coffeescript
# Here we are hacking karma mocha. Note how similar it is to karma-mocha's
# existing `initMocha` function. We splice out the karma-mocha adapter, such
# that later (see the 'srcFiles' variable in this file), we can load the
# karma-mocha adapter after bdd-lazy-var.
karmaMocha = require('karma-mocha')
initMocha = karmaMocha['framework:mocha'][1]
karmaMocha['framework:mocha'][1] = (files) ->
  initMocha.apply(this, arguments)
  files.splice(1, 1)
karmaMocha['framework:mocha'][1].$inject = [ 'config.files', 'config.client.mocha' ]

module.exports = (config) ->
	specs = ['spec/**']
	srcFiles = ['node_modules/bdd-lazy-var/bdd_lazy_var_global.js']
	srcFiles.push(require.resolve('karma-mocha/lib/adapter'))

	config.set
		basePath: ''
		frameworks: [ 'mocha' ]
		files: srcFiles.concat(specs)
		...
```

I do not get the message I mentioned before ("This seems to be a pre-built javascript file..."). Great!

Previously I had asked what the `-u` and `--src` stuff was in the command line arguments to `karma start`. It turns out they are arbitrary (you could make up your own), and then karma passes them to you attached to the `config` parameter. So normally where you would call `config.set(...)`, you could use those arguments by referring to e.g. `config.u`, `config.src`, etc.
